version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    networks:
        - demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aco
  react:
    image: react:1.0
    ports:
      - "3000:3000"
    networks:
        - demo
    tty: true
    environment:
     CHOKIDAR_USEPOLLING: "true"
    build:
        context: ./clientfrontend
        args:
            REACT_APP_HOST_IP_ADDRESS: zuul
    volumes:
        - /app/node_modules
    depends_on:
        - eureka
        - database
        - auth
        - car
        - code
  eureka:
    image: eureka:1.0
    ports:
      - "8761:8761"
    networks:
        - demo
    tty: true
  auth:
    image: auth:1.0
    ports:
      - "8085:8085"
    networks:
        - demo
    tty: true
    environment:
      DB_HOST: database
      REGISTRY_HOST: eureka
    depends_on:
        - eureka
        - database
  car:
    image: car:1.0
    ports:
      - "8081:8081"
    networks:
        - demo
    tty: true
    environment:
      DB_HOST: database
      REGISTRY_HOST: eureka
    depends_on:
        - eureka
        - database
  code:
    image: code:1.0
    ports:
      - "8086:8086"
    networks:
        - demo
    tty: true
    environment:
      DB_HOST: database
      REGISTRY_HOST: eureka
    depends_on:
        - eureka
        - database         
  zuul:
    image: zuul:1.0
    ports:
      - "8762:8762"
    networks:
        - demo
    environment:
      REGISTRY_HOST: eureka
    tty: true
    depends_on:
        - eureka
        - auth
        - car
        - code
networks:
  demo:
    name: demo
    driver: bridge
