//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.soapserveryt.api.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soapserveryt.api.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soapserveryt.api.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClientRequestComment }
     * 
     */
    public ClientRequestComment createClientRequestComment() {
        return new ClientRequestComment();
    }

    /**
     * Create an instance of {@link ClientRequestRentalRequestId }
     * 
     */
    public ClientRequestRentalRequestId createClientRequestRentalRequestId() {
        return new ClientRequestRentalRequestId();
    }

    /**
     * Create an instance of {@link ServerRespond }
     * 
     */
    public ServerRespond createServerRespond() {
        return new ServerRespond();
    }

    /**
     * Create an instance of {@link ClientRequestRentalRequest }
     * 
     */
    public ClientRequestRentalRequest createClientRequestRentalRequest() {
        return new ClientRequestRentalRequest();
    }

    /**
     * Create an instance of {@link ClirentRequestOccupancy }
     * 
     */
    public ClirentRequestOccupancy createClirentRequestOccupancy() {
        return new ClirentRequestOccupancy();
    }

    /**
     * Create an instance of {@link ClientRequest }
     * 
     */
    public ClientRequest createClientRequest() {
        return new ClientRequest();
    }

    /**
     * Create an instance of {@link ClientRequestSetMileageAndDescription }
     * 
     */
    public ClientRequestSetMileageAndDescription createClientRequestSetMileageAndDescription() {
        return new ClientRequestSetMileageAndDescription();
    }

}
